In [1]:
#create an array
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 4]
 [5 8 7]]


In [2]:
#create an array with full of zeros value
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
#create an array with random value
d=np.random.random ((2,2))
print("Random array:\n",d)

Random array:
 [[0.69365651 0.84190068]
 [0.35958728 0.9649641 ]]


In [6]:
#create a sequence of integers from 0 to 30 with step of 5
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [7]:
#Reshaping 3*4 array to 2*2*3 array
import numpy as arr
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [8]:
#flatten array
flarr=arr.flatten()
print("\n Original array:\n",arr)
print("\n Flattened array:\n",flarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [9]:
print("\n No of dimensions:\n",arr.ndim)
print("\nshape of array:\n",arr.shape)
print("\nsize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\n converted array  element:\n",newtype)
print("\n converted array type:\n",newtype.dtype)


 No of dimensions:
 2

shape of array:
 (3, 4)

size of array:
 12

Array type:
 int64

 converted array  element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 converted array type:
 float32
