<a href="https://colab.research.google.com/github/240901064/Python-programming-for-machine-learning-/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
scores=np.array([45,78,56,89,90,67,34,23,88,76,54,61,72,48,59,92,81,39,64,70])
average=np.mean(scores)
highest=np.max(scores)
lowest=np.min(scores)
print("Average Score:",average)
print("Lowest Score:",highest)
print("Lowest Score:",lowest)
pass_mark=50
print("\nPass/Fail Status")
for i,score in enumerate(scores):
  if score >=pass_mark:
    print(f"Student {i+1}: Pass")
  else:
    print(f"Student {i+1}:Fail")
print("\nGrades")
for i, s in enumerate(scores):
  if s >=90:
    grade="A"
  elif s >=75:
    grade="B"
  elif s >=60:
    grade="C"
  elif s >=50:
    grade="D"
  else:
    grade = "F"
  print("Student",i+1,"Grade:",grade)

Average Score: 64.3
Lowest Score: 92
Lowest Score: 23

Pass/Fail Status
Student 1:Fail
Student 2: Pass
Student 3: Pass
Student 4: Pass
Student 5: Pass
Student 6: Pass
Student 7:Fail
Student 8:Fail
Student 9: Pass
Student 10: Pass
Student 11: Pass
Student 12: Pass
Student 13: Pass
Student 14:Fail
Student 15: Pass
Student 16: Pass
Student 17: Pass
Student 18:Fail
Student 19: Pass
Student 20: Pass

Grades
Student 1 Grade: F
Student 2 Grade: B
Student 3 Grade: D
Student 4 Grade: B
Student 5 Grade: A
Student 6 Grade: C
Student 7 Grade: F
Student 8 Grade: F
Student 9 Grade: B
Student 10 Grade: B
Student 11 Grade: D
Student 12 Grade: C
Student 13 Grade: C
Student 14 Grade: F
Student 15 Grade: D
Student 16 Grade: A
Student 17 Grade: B
Student 18 Grade: F
Student 19 Grade: C
Student 20 Grade: C


In [ ]:
A=np.array([[2,3],[1,2]])
b=np.array([8,5])
x=np.linalg.solve(A,b)
print("Solution of x:")
print(x)


Solution of x:
[1. 2.]


In [ ]:
import numpy as np
steps=np.array([5000,6200,7000,8000,9000,6500,7200,8100,9500,4000])
print("Total steps:",steps.sum())
print("Average steps:",steps.mean())
print("Maximum steps:",steps.max())
print("\nHigh activity days(>8000):")
for i in range(len(steps)):
  if steps[i] > 8000:
    print("Day",i+1,":",steps[i])

Total steps: 70500
Average steps: 7050.0
Maximum steps: 9500

High activity days(>8000):
Day 5 : 9000
Day 8 : 8100
Day 9 : 9500


In [ ]:
import numpy as np

# Marks of students in Math, Science, English
marks = np.array([
[78,85,90],
[65,70,72],
[88,92,95],
[55,60,58],
[80,75,82]
])

subjects = ["Math","Science","English"]

# Average
avg = marks.mean(axis=0)

# Highest
high = marks.max(axis=0)

# Lowest
low = marks.min(axis=0)

for i in range(3):
    print(subjects[i])
    print("Average:",avg[i])
    print("Highest:",high[i])
    print("Lowest:",low[i])
    print()


Math
Average: 73.2
Highest: 88
Lowest: 55

Science
Average: 76.4
Highest: 92
Lowest: 60

English
Average: 79.4
Highest: 95
Lowest: 58



In [ ]:
import numpy as np

Z1 = 10 + 5j
Z2 = 8 - 3j
Z3 = 6 + 2j


Z_series = Z1 + Z2 + Z3


Z_parallel = 1 / (1/Z1 + 1/Z2 + 1/Z3)

print("Impedance Z1 =", Z1)
print("Impedance Z2 =", Z2)
print("Impedance Z3 =", Z3)

print("Total Series Impedance =", Z_series)
print("Total Parallel Impedance =", Z_parallel)

Impedance Z1 = (10+5j)
Impedance Z2 = (8-3j)
Impedance Z3 = (6+2j)
Total Series Impedance = (24+4j)
Total Parallel Impedance = (2.8849063190969395+0.4154544396601886j)


In [ ]:
import numpy as np


stock1 = np.array([
    [100,110,95],
    [102,112,97],
    [105,115,100],
    [108,118,102],
    [110,120,105]
])
stock2 = np.array([
    [98,108,94],
    [101,111,96],
    [103,113,98],
    [107,117,101],
    [109,119,104]
])


sum_matrix = stock1 + stock2


diff_matrix = stock1 - stock2

print("Stock 1 Data:\n",stock1)
print("Stock 2 Data:\n",stock2)

print("Element-wise Sum:\n",sum_matrix)
print("Element-wise Difference:\n",diff_matrix)

Stock 1 Data:
 [[100 110  95]
 [102 112  97]
 [105 115 100]
 [108 118 102]
 [110 120 105]]
Stock 2 Data:
 [[ 98 108  94]
 [101 111  96]
 [103 113  98]
 [107 117 101]
 [109 119 104]]
Element-wise Sum:
 [[198 218 189]
 [203 223 193]
 [208 228 198]
 [215 235 203]
 [219 239 209]]
Element-wise Difference:
 [[2 2 1]
 [1 1 1]
 [2 2 2]
 [1 1 1]
 [1 1 1]]


In [ ]:
import pandas as pd

# EEG sample data
data = {
    "Electrode1":[10,12,11,13,15],
    "Electrode2":[8,9,10,9,11],
    "Electrode3":[14,13,15,16,14]
}

df = pd.DataFrame(data)

print("EEG Data:\n",df)

print("\nMean Values:\n",df.mean())
print("\nVariance:\n",df.var())
print("\nPeak Values:\n",df.max())

EEG Data:
    Electrode1  Electrode2  Electrode3
0          10           8          14
1          12           9          13
2          11          10          15
3          13           9          16
4          15          11          14

Mean Values:
 Electrode1    12.2
Electrode2     9.4
Electrode3    14.4
dtype: float64

Variance:
 Electrode1    3.7
Electrode2    1.3
Electrode3    1.3
dtype: float64

Peak Values:
 Electrode1    15
Electrode2    11
Electrode3    16
dtype: int64


In [ ]:
import pandas as pd

data = {
'Product':['Laptop','Smartphone','Tablet','Monitor','Keyboard'],
'Price':[1200,800,400,300,50],
'Quantity':[10,25,15,8,40]
}

df = pd.DataFrame(data)

print("Inventory Data:\n",df)

# Total value of each product
df["Total_Value"] = df["Price"] * df["Quantity"]

print("\nUpdated Inventory:\n",df)

print("\nTotal Inventory Value =", df["Total_Value"].sum())

Inventory Data:
       Product  Price  Quantity
0      Laptop   1200        10
1  Smartphone    800        25
2      Tablet    400        15
3     Monitor    300         8
4    Keyboard     50        40

Updated Inventory:
       Product  Price  Quantity  Total_Value
0      Laptop   1200        10        12000
1  Smartphone    800        25        20000
2      Tablet    400        15         6000
3     Monitor    300         8         2400
4    Keyboard     50        40         2000

Total Inventory Value = 42400
