In [2]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Original array:\n",arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [3]:
#returns every other rows
print("\nEvery other rows:\n",arr[0:3:2])


Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [6]:
#return every other element from the entire array
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr[::2]: [1 3 5 7]


In [9]:
#slicing array
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:\n",temp)


Array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [10]:
#integer array indexing
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1)" "(3,0):\n",temp)


Elements at indices(0,3),(1,2),(2,1)(3,0):
 [4. 6. 0. 3.]


In [11]:
#boolean array indexing
cond=arr>2
#cond is a boolean array
te=arr[cond]
print("\nElements greater than 2:\n",te)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [13]:
import numpy as np
#joining  two array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [14]:
#horizontal join
arr3=np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [16]:
#vertical join
arr4=np.vstack((arr1,arr2))
print(arr4)

[[1 2 3]
 [4 5 6]]


In [18]:
#depth join
arr5=np.dstack((arr1,arr2))
print(arr5)

[[[1 4]
  [2 5]
  [3 6]]]


In [20]:
#splitting array
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
